#!/bin/sh

set -e

installinit_error() {
	status=$?
	start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/ntpd.pid && exit 0
	exit $status
}

# Automatically added by dh_installinit/12.1.1
if [ -x "/etc/init.d/ntp" ]; then
	invoke-rc.d ntp stop || installinit_error
fi
# End automatically added section

